name: mdl-noopeneye
channels:
  - pytorch
  - conda-forge
  - openeye
  - nvidia
  - dglteam

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pytorch 
  - torchvision 
  - torchaudio 
  - cudatoolkit=11.3
  - openeye-toolkits
  - scikit-learn
  - pandas
  - tqdm
  - dgl
  - pip
  - autopep8
  - pip:
    - git+https://github.com/mariogeiger/se3cnn.git
